CREATE TABLE telegram_accounts (
    id VARCHAR(255) PRIMARY KEY,
    phone_number VARCHAR(255),
    status VARCHAR(255)
);

CREATE TABLE leads (
    id VARCHAR(255) PRIMARY KEY,
    username VARCHAR(255),
    phone_number VARCHAR(255)
);

CREATE TABLE conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_account_id VARCHAR(255),
    lead_id VARCHAR(255),
    lead_username VARCHAR(255),
    last_message VARCHAR(2000),
    last_message_timestamp TIMESTAMP WITH TIME ZONE
);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_account_id VARCHAR(255),
    lead_id VARCHAR(255),
    content VARCHAR(2000),
    direction VARCHAR(255),
    status VARCHAR(255),
    timestamp TIMESTAMP WITH TIME ZONE
);
