-- V5__warm_up_tasks.sql
-- Description: Table schemas for tracking warm-up tasks.
-- JTBD: When implementing warm-up routines, I want to execute channel subscriptions and read actions.

CREATE TABLE warm_up_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    channel_username VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL, -- e.g. PENDING, COMPLETED, FAILED
    subscribed BOOLEAN NOT NULL DEFAULT FALSE,
    marked_as_read BOOLEAN NOT NULL DEFAULT FALSE,
    executed_at TIMESTAMP WITH TIME ZONE,
    applied_delay_ms BIGINT,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
