-- V4__warm_up_schema.sql
-- Description: Table schemas for tracking account, age, warm-up state, and warm-up cycles.
-- JTBD: When implementing schema for this epic, I want to track account age and warm-up state, so that I can maximize account lifespan and trust scores.

CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id VARCHAR(255) UNIQUE NOT NULL,
    phone_number VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    warm_up_status VARCHAR(50) NOT NULL, -- e.g. NOT_STARTED, IN_PROGRESS, COMPLETED
    trust_score DOUBLE PRECISION NOT NULL DEFAULT 0.0
);

CREATE TABLE warm_up_cycles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(50) NOT NULL, -- e.g. ACTIVE, COMPLETED, FAILED
    target_score_increase DOUBLE PRECISION NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);

-- Down migration (documented rollback):
-- DROP TABLE warm_up_cycles;
-- DROP TABLE accounts;
